services:
  server:
    image: "ghcr.io/android-sms-gateway/twilio-fallback:latest"
    build:
      context: .
      target: final
    environment:
      - HTTP__ADDRESS=:3000
      - HTTP__PROXY_HEADER=X-Forwarded-For
      - HTTP__PROXIES=127.0.0.1
      - TWILIO__ACCOUNT_SID=${TWILIO__ACCOUNT_SID}
      - TWILIO__AUTH_TOKEN=${TWILIO__AUTH_TOKEN}
      - SMSGATE__USERNAME=${SMSGATE__USERNAME}
      - SMSGATE__PASSWORD=${SMSGATE__PASSWORD}
    ports:
      - 3000:3000
