FROM --platform=$BUILDPLATFORM gcr.io/distroless/static-debian12:latest


ENV HTTP__ADDRESS=:3000

# Copy the Pre-built binary file from GoReleaser
COPY twilio-fallback /bin/twilio-fallback

# Expose port 3000 to the outside world
EXPOSE 3000

# Command to run the executable
ENTRYPOINT ["/bin/twilio-fallback"]
