// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "SMSGate Support",
            "email": "support@sms-gate.app"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/twilio": {
            "post": {
                "description": "Processes Twilio message status updates with signature validation",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "tags": [
                    "Twilio"
                ],
                "summary": "Handle Twilio message status callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Twilio message SID",
                        "name": "MessageSid",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Message status (e.g. delivered, failed)",
                        "name": "MessageStatus",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Twilio request signature",
                        "name": "X-Twilio-Signature",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "{{VERSION}}",
	Host:             "[YOUR_SERVICE_URL]",
	BasePath:         "",
	Schemes:          []string{"https"},
	Title:            "SMSGate Twilio Fallback API",
	Description:      "Provides a fallback for Twilio SMS messages via SMSGate",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
